services:
  redis:
    image: docker.io/library/redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: docker.io/library/postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
