name: Build and Push docker image
on: workflow_dispatch

jobs:
  image:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker repository
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false
      -
        name: Build base
        uses: docker/build-push-action@v6
        with:
          load: true
          file: Dockerfile.base
          tags: outlinewiki/outline-base:latest
      -
        name: Build and Push release
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_TAG }}
